#!/bin/bash
#SBATCH -J Project5
#SBATCH -A cs475-575
#SBATCH -p class
#SBATCH --gres=gpu:1
#SBATCH -o Project5.out
#SBATCH -e Project5.err
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=mamel@oregonstate.edu
#number of threads:
for t in 16 32 64 128
do
	#echo NUMT = $t
	#number of subdivisions:
	for s in 1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192
	do
		#echo NUMS = $s
		/usr/local/apps/cuda/cuda-10.1/bin/nvcc -DNUMTRIALS=$s -DBLOCKSIZE=$t Project5.cu -o prog
		./prog
	done
done